# Generated by Django 4.1.4 on 2025-02-08 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_id', models.IntegerField()),
                ('driver_id', models.IntegerField()),
                ('petrol_type', models.CharField(choices=[('RON95', 'RON 95'), ('RON97', 'RON 97'), ('RON100', 'RON 100'), ('Diesel', 'Diesel')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('order_status', models.TextField(default='Waiting for vendor response.')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delivery_address', models.CharField(max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
