# Generated by Django 4.1.4 on 2025-02-11 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_order_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('petrol_type', models.CharField(choices=[('RON95', 'RON 95'), ('RON97', 'RON 97'), ('RON100', 'RON 100'), ('Diesel', 'Diesel')], max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_liter', models.DecimalField(decimal_places=2, max_digits=6)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='app.vendor')),
            ],
            options={
                'unique_together': {('vendor', 'petrol_type')},
            },
        ),
    ]
