# Generated by Django 4.1.4 on 2025-02-10 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_vendor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='user',
        ),
    ]
