# Generated by Django 4.1.4 on 2025-02-10 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_driver_accepted_orders_driver_completed_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='driver_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='vendor_id',
        ),
        migrations.AddField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app.driver'),
        ),
    ]
