# Generated by Django 4.1.4 on 2025-02-11 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
