----------------------Q1----------------------
CREATE TABLE ORDERS (
ORDER_ID		INTEGER NOT NULL,
ORDER_DATE		DATE,
REQUIRED_DATE	DATE,
SHIPPED_DATE	DATE,
CUST_ID			INTEGER,
PRIMARY KEY (ORDER_ID),
FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER
);

----------------------Q2----------------------
SELECT CUST_NAME, CUST_PHONE
FROM CUSTOMER C, ORDERS O
WHERE C.CUST_ID = O.CUST_ID
AND C.CUST_CITY = 'Cyberjaya'
AND O.ORDER_DATE = '2021-09-27'
ORDER BY CUST_NAME ASC;

----------------------Q3----------------------
SELECT PRODUCT_NAME, QUANTITY_ORDERED * PRICE_EACH AS TOTAL_ORDERED_PRICE
FROM PRODUCT P, ORDER_DETAILS OD
WHERE P.PRODUCT_ID = OD.PRODUCT_ID
GROUP BY PRODUCT_NAME;

----------------------Q4----------------------
UPDATE ORDER_DETAILS
SET TRACKING = 'depart from station'
WHERE ORDER_ID = 12333;

----------------------Q5----------------------
CREATE TRIGGER SET_STATUS
AFTER INSERT ON ORDER_DETAILS
FOR EACH ROW MODE DB2SQL 
BEGIN
	UPDATE ORDER_DETAILS
	SET STATUS = 'Need Approval'
	WHERE QUANTITY_ORDERED * PRICE_EACH > 20000;
END