# Generated by Django 4.1.4 on 2025-02-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_vendor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='accepted_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='completed_orders',
            field=models.IntegerField(default=0),
        ),
    ]
